// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dpspjctgftondswgrlpo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwc3BqY3RnZnRvbmRzd2dybHBvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQyNjU1NTgsImV4cCI6MjA0OTg0MTU1OH0.CrzmK7o6u7uTNMidsWFCfoSc_ZVuaIJfzU9nlnyNtbk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);